### ISSUE TITLE
lifecycle return value regression

### ISSUE THREAD

**Issue by john-shaffer** [donut-party/system#16]
There seems to be a contradiction between the docs and the code, and I'm not 100% sure which is supposed to be correct. The README says,

> The rules for handling return values are:
> 
>     If a system map is returned, convey that forward
>     Otherwise, if this is a lifecycle function (::ds/pre-start or ::ds/post-start) ignore the return value
>     Otherwise, this is a signal handler (:ds/start). Place its return value under ::ds/instances.
> 

But `handler-stage-fn` seems to do the opposite, only placing the return value under `::ds/instances` when it is a lifecycle function.

```clojure
            result-key   (if (= :lifecycle (get-in system [::signals (last computation-stage-node) :signal-type]))
                           ::instances
                           (last computation-stage-node))
```

Upgrading donut.system caused my tests to fail, so I isolated the issue to this test case:

```clojure
(deftest custom-signal-test
  (is (= {:group-a
          {:a
           {:name            [:group-a :a]
            :config          nil
            :resolved-config nil
            :instance        {:custom/signal true :started true}
            :dependencies    #{}
            :status nil
            :doc nil}}}
         (->
          {::ds/defs {:group-a {:a #::ds{:start (fn [_] {:started true})
                                         :custom/signal (fn [{::ds/keys [instance]}] (assoc instance :custom/signal true))}}}
           ::ds/signals
           {:custom/signal {:order :topsort :signal-type :lifecycle}}}
          ds/start
          (ds/signal :custom/signal)
          ds/describe-system))))
```

Prior to e18f3932071dae6a3ed363768bbc0a1315a77971, this passes without needing a `:signal-type`. Afterwards, it requires `:signal-type :lifecycle` to pass.

It looks to me like the meaning of lifecycle fn was intentionally changed, but the docs were not. I'm fine with changing my code to match, but I wanted to confirm what the intended behavior is. And I'm curious about the reason for the changes, if you don't mind elaborating.

**Comment by flyingmachine** [comment]
Oh shoot, good catch. Somewhere along the way I changed my thinking on how to use the word "lifecycle" without realizing it. Maybe instead of `:lifecycle` I should use something like `:returns-instance-value?` as that is more directly what's happening here.

But yes going forward, signals handlers need to opt-in to having their return value set the instance value

**Comment by flyingmachine** [comment]
OK, I've pushed a  new release that uses `:returns-instance?` instead of `:lifecycle`. Sorry this bit you! But thank you for reporting it.

**Comment by flyingmachine** [comment]
New version is `party.donut/system {:mvn/version "0.0.204"}`
