### ISSUE TITLE
Direct access to Constant instances from components

### ISSUE THREAD

**Issue by velios** [donut-party/system#26]
Hello and first of all thank you for great tool. Constant Instances mentioned in docs as syntactic sugar. Since they are mutable and stay unchangeable during system assembly, why not make it possible to reference them in components? I think this could make the system map even more expressive. How do you think?

```clojure
;; content of base.edn
{:jetty-options
 {:port 8888
  :join? false}
 :handler-optoions
   {:def-msg "hi from config}

;; define all behavior in base-system
(def base-system
  {::ds/defs
   {:env (read-file "config/base.edn")

    :http
    {:server
     #::ds{:start  (fn [_]
                     (let [options (ds/const-ref [:env :jetty-options])
                           (rj/run-jetty handler options)])
           :stop   (fn [{::ds/keys [instance]}]
                     (.stop instance))
           :config {:handler (ds/ref [:http :handler])}}

     :handler
     #::ds{:start (fn [_]
                    (prn "message from config =>" (ds/const-ref [:env :handler-options :def-msg])
                    ;; handler goes here
                    )}}}})
```

You are already know what Instances are constant before assembly. I think because thay don't contain ::ds/start key. The idea came from trying to transfer a working project to a donut system. It is very confusing that the config must be uploaded twice, although I know for sure that it is immutable. Maybe not even need special ds/const-ref fn.

**Comment by flyingmachine** [comment]
I think you can actually do this already, though not quite like in your example. I believe a signal handler like this should do the trick:

``` clojure
(fn [{:keys [::ds/system]}]
  (prn "from system" (ds/instance system [:env :db-jetty-option])))
```

**Comment by velios** [comment]
@flyingmachine I also thought this trick would work, but it doesn't. If you do not place a link inside the config section for a component, then it will not end up in the instance in the start section. You can check the example I gave above and see for yourself. This is the problem, there are constant instances that do not need to be prepared and calculated in any way, but they are not available to us, like another type of instance that does not make sense without prior initialization, such as thread pools or a database connection.

**Comment by velios** [comment]
i think it's work like this because order of "instanciate" of constant components not determinate. But i think they have to load before other type of components and available from ::ds/system at the moment of they requested from another non-constant components

**Comment by flyingmachine** [comment]
Thank you for the details! I hope to look into this more soon.

**Comment by flyingmachine** [comment]
OK I think I understand what's going on:

* They `::ds/instances` key gets populated as the start signal is applied to each component, in order. The order matters
* Putting in refs with `ds/ref` ensures the correct order. Without it, you can't guarantee that a component instance will be present under `::ds/instances`. Therefore, you can't rely on `(ds/instance system...)` as I had suggested

However, it's still possible to access the value without having to put it in the config:

``` clojure
(fn [{:keys [::ds/system]}]
  (prn "from system" (get-in system [::ds/defs :env :db-jetty-option])))
```

Could you let me know if this works for you?

**Comment by velios** [comment]
>Could you let me know if this works for you?

@flyingmachine Great, this work! For some reason, it never occurred to me to look at what was included in the arguments to the start function. But there is a lot there. Including a pre-computed complete map of the system(::ds/system). It feels like something for internal needs, but why not use it. 

Is it worth documenting this feature or should it still be considered a hack not recommended for real use?

While checking, I discovered an interesting point. It turns out that the config and stop keys will appear in the arguments only if they are specified. You can also put anything in stop and it won’t even prevent the system from rebooting correctly. At least in cases where there are no dependencies.

<img width="549" alt="image" src="https://github.com/donut-party/system/assets/9293462/c3253438-d32e-470e-9bd0-06b05794ffb0">
